### ISSUE TITLE
Campaign Entity

### ISSUE THREAD

**Issue by manasiNeo** [manasiNeo/CrowdFundingRepo#27]
The campaign is created by the user and the attributes it must have are:

- campaignId 
- title
- description 
- goalAmount
- raisedAmount 
- pendingAmount
- startDate 
- endDate
- userId
- category 
- status

The functionalites that a campaigner can do is:

1. createCampaign()
2. viewCampaign()
3. updateCampaign()
4. deleteCampaign()
5. viewContributors()

**Comment by shanmugamayan-milaap** [comment]
Completed
